[package]
name = "jcdrs"
version = "0.0.1"
authors = ["SiIky <siiky@users.noreply.github.com>"]
repository = "https://github.com/siiky/jcdrs"

[dependencies]
clap = "*"
unicode-normalization = "*"
unicode-jp = "*"
